name: basic
on:
  push:
    tags: [ "v*" ]
    branches: [ master ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: build-dialoguss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - name: run go mod
        run: go mod tidy && go build
      - name: Run dblstd check
        run: |
          git clone https://github.com/sethbonnie/dblstd dbstd-src
          go build -o dbstld ./dblstd-src/main.go && chmod +x ./dblstd
          dblstd -s .dblstd .